name: widgetbook_hosting
description: A simple command-line application.

environment:
  sdk: '>=2.15.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  very_good_analysis: ^2.4.0
dependencies: 
  archive: ^3.1.8
  args: ^2.3.0
  dio: ^4.0.4
