name: cli
description: A simple command-line application.

environment:
  sdk: '>=2.15.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.10
  freezed: ^2.0.3
  json_serializable: ^6.2.0
  lints: ^1.0.0
dependencies: 
  args: ^2.3.0
  file: ^6.1.2
  freezed_annotation: ^2.0.3
  parser:
    path: ../parser
  version: ^2.0.0
