name: cli
description: A simple command-line application.

environment:
  sdk: '>=2.15.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  args: ^2.3.0
  git: ^2.0.0
  helper:
    path: ../helper
  parser:
    path: ../parser
