name: cli
description: A command-line application to upload Widgetbook builds to Widgetbook Cloud.

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.10
  freezed: ^2.0.3
  json_serializable: ^6.2.0
  lints: ^1.0.0
dependencies: 
  archive: ^3.3.0
  args: ^2.3.0
  dio: ^4.0.6
  file: ^6.1.2
  test: ^1.12.1
  freezed_annotation: ^2.0.3
  git:
    git:
      url: https://github.com/JensHor/git.git
      ref: feat/diff
  parser:
    path: ../parser
  version: ^2.0.0
