on: 
  pull_request:
    paths:
      - "packages/bitbucket/**"
      - ".github/workflows/bitbucket.yaml"
  push:
    branches:
      - main
name: bitbucket
jobs:
  build:
    name: build
    defaults:
      run:
        working-directory: packages
    runs-on: ubuntu-latest
    needs: [test, code-quality]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build Docker Image
      run: docker build -t widgetbook/widgetbook-hosting-bitbucket:dev -f "bitbucket/Dockerfile" .

    - name: Push Docker Image to Artifact Registry
      run: |
        docker push widgetbook/widgetbook-hosting-bitbucket:dev