on: 
  pull_request:
    paths:
      - "packages/cli/**"
      - ".github/workflows/cli.yaml"

name: cli
jobs:
  build:
    name: build
    defaults:
      run:
        working-directory: packages/cli
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@v1

    - name: Install dependencies
      run: dart pub get

    - name: Build AOT-compiled CLI
      run: dart compile aot-snapshot bin/cli.dart -o cli-v1.aot

    - name: Authenticate Service Account
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.STORAGE_SERVICE_ACCOUNT }}

    - name: Run ls
      run: ls

    - name: Upload folder
      uses: google-github-actions/upload-cloud-storage@v0.4.0
      with:
        path: packages/cli/cli-v1.aot 
        destination: widgetbook-cloud.appspot.com/tools
        parent: false