on: 
  pull_request:
    paths:
      - "packages/github/**"
      - ".github/workflows/github.yaml"

name: github
jobs:
  build:
    name: build
    defaults:
      run:
        working-directory: packages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build Docker Image
      run: docker build -t widgetbook/widgetbook-hosting-github:dev -f "github/Dockerfile" .

    - name: Push Docker Image to Artifact Registry
      run: |
        docker push widgetbook/widgetbook-hosting-github:dev